### ISSUE TITLE
[Home] - Adequar responsividade

### ISSUE THREAD

**Issue by caiquefonseca** [SouJunior/vagas-webapp#260]

**Comment by max-faria** [comment]
Figma ref: https://www.figma.com/file/e6ULjE20hGthvbpoLPq2qZ/Portal-de-Vagas?type=design&node-id=1211-4864&mode=design&t=BiEFBYYtZ3d3Qmer-0

**Comment by jhonatancostaamaral** [comment]
Bug referente a task:
https://github.com/orgs/SouJunior/projects/3/views/1?filterQuery=label%3A%22squad+cereal+killers+-+vagas%22&pane=issue&itemId=31655596

**Comment by valtertxba** [comment]
- Na versao mobile com a resoluçao 320x675 o icone da logo desaparece.
- Mais abaixo da pagina, secao ''Vamos junstos nesta joarnada" responsivida ficou ok, porem um pouco mais abaixo, quebrou um detalhe no retangulo em volta dos depoimentos.
- Em outros modelos de dispositivos moveis, apresentou alguns erros de responsividade em outros locais.
Evidencias:


![Image](https://github.com/SouJunior/vagas-webapp/assets/125107825/890ae1db-1428-4e68-90ae-66d5722e028b)
![Image](https://github.com/SouJunior/vagas-webapp/assets/125107825/b76b2422-0408-44dd-98ed-30ac4794b267)
![Image](https://github.com/SouJunior/vagas-webapp/assets/125107825/332dffcc-83d9-4987-a2dd-ef6747c38a30)

@jjsalim @CamilaRoch @pm-marcelocarvalho

**Comment by alnogueirati** [comment]
mesma demanda da [Home] - Responsividade da Home #207

segue link com análise dos testes realizados, esta demanda foi reprovada parcialmente pois há alguns ajustes que precisam ser realizados conforme demonstrados no arquivo no link:

https://docs.google.com/document/d/e/2PACX-1vQhpWgOpikSMVTlr33gplq1Eg5I0kNl9mc9Nt7zZIIEJyFCEP-vknUQE8u28konyZebbZ65EWOaOHhZ/pub
