### ISSUE TITLE
[US- 342] - [Home/Mobile] Ajuste  Campo para pesquisar vagas 

### ISSUE THREAD

**Issue by marleypm16** [SouJunior/vagas-webapp#346]
Ajuste - Campo para pesquisar vagas
[#342](https://github.com/SouJunior/vagas-webapp/issues/342)

**Comment by marleypm16** [comment]
Aguardando aprovar pr

**Comment by ariadnamorais** [comment]
@Aline-Frecceiro pode realizar o teste nesse link:

https://deploy-preview-363--vagas-front-end.netlify.app/

**Comment by Aline-Frecceiro** [comment]
Os testes foram realizados em Desktop/Mobile.

@marleypm16 @ariadnamorais @Myrellasp @wouerner 
Os Testes no Desktop foram aprovados, estão conforme os cenários exigidos.
Foram testados em dois modelos de Celular Samsung S20 e Iphone 11, estão quebrando textos, tem textos atrás da caixinha de diálogo.

Segue documentação com os Cenários de Testes e Evidências de Testes:

https://docs.google.com/document/d/1i6CRVY6cMEQu-smbZo4iqMQbLWrN_to0lv1ExWlDNn4/edit?usp=sharing

**Comment by marleypm16** [comment]
repassar para a squad de resolução de bugs
