### ISSUE TITLE
[Home] Mobile - Comportamento 

### ISSUE THREAD

**Issue by marleypm16** [SouJunior/vagas-webapp#347]
Ajustar comportamento da home page - US https://github.com/SouJunior/products/issues/653

![Image](https://github.com/user-attachments/assets/6648fa15-d117-44ba-9bbc-341d6fd5c78f)

**Comment by alnogueirati** [comment]
Demanda igual a [Home] Mobile - Comportamento #653, e a mesma se encontra aprovada visto que o erro foi corrigido conforme teste realizado.
